# Generated by Django 3.0.7 on 2020-07-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date_published', models.DateField(auto_now=True, verbose_name='Дата публікації')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('is_price_final', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('reg_date', models.DateField(auto_now=True, verbose_name='Дата реєстрації')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефону')),
                ('is_show_phone', models.BooleanField(default=False, verbose_name='Показувати телефон')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='Область')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер будинку')),
                ('apartments', models.CharField(max_length=5, verbose_name='Номер квартири')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User', verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='SellerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Оцінка (0-5)')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_for_feedback', to='website.User', verbose_name='Продавець')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.User', verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='AdvertPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Advert', verbose_name='Оголошення')),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.UserAddress', verbose_name='Адреса відправлювача'),
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User', verbose_name='Власник'),
        ),
    ]
