# Generated by Django 3.0.7 on 2020-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterModelOptions(
            name='advertphoto',
            options={'verbose_name': 'Фото оголошення', 'verbose_name_plural': 'Фото оголошення'},
        ),
        migrations.AlterModelOptions(
            name='sellerfeedback',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Адреса', 'verbose_name_plural': 'Адреси'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
    ]
