# Generated by Django 3.0.7 on 2020-07-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200727_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='images/default-no-image.png', upload_to='images/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.UserAddress', verbose_name='Адреса відправлювача'),
        ),
        migrations.AlterField(
            model_name='advertphoto',
            name='image',
            field=models.ImageField(default='images/default-no-image.png', upload_to='images/', verbose_name='Зображення'),
        ),
    ]
