# Generated by Django 3.0.7 on 2020-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200729_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='poster',
        ),
        migrations.AddField(
            model_name='advertphoto',
            name='is_cover_photo',
            field=models.BooleanField(default=False, verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='advertphoto',
            name='image',
            field=models.ImageField(default='images/default-no-image.img', upload_to='images/', verbose_name='Зображення'),
        ),
    ]
