# Generated by Django 3.0.7 on 2020-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200731_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='date_published',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публікації'),
        ),
    ]
