# Generated by Django 3.0.7 on 2020-08-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200803_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
