# Generated by Django 3.0.7 on 2020-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contactinfo_deliverytype_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
