# Generated by Django 3.0.7 on 2020-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200806_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RemoveField(
            model_name='advert',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='is_reviewed',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_anonymous_sale',
            field=models.BooleanField(default=True),
        ),
    ]
